networks:
  pg-net:
    external: true

services:
  qualite-redis:
    image: redis:7.2-alpine
    container_name: redis-qualite
    ports:
      - "6369:6379"
    networks:
      - pg-net
    environment:
      - TZ=Europe/Paris
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --requirepass redis-qual-dev

volumes:
  redisdata: